package com.henrikstabell.fogworld.config.biomesconfig;

import net.minecraft.client.Minecraft;

import java.io.File;

public class BiomeConfigReader {

    private static final File configDir = new File(Minecraft.getInstance().gameDirectory + "/config/fogworld/biomes");

    /**
     * Reads the JSON config files that have been generated by {@link BiomeConfigGenerator} for every biome registered to the Forge Biome Registry.
     * TODO: VERY ALPHA! SUBJECT TO CHANGE!
     */
    public static void readBiomeConfigs() {

    }

}
